### ISSUE TITLE
Debugの出力がわかりにくい

### ISSUE THREAD

**Issue by higumachan** [taiheioki/state-set#2]
```
StateSet {
    data: 8,
    phantom: PhantomData<Hoge>,
}
```

現状だと、#1 と同じように謎のビット列を数値化したデータになっていて分かりづらい。
#1 と同じような形で出力したい。

**Comment by taiheioki** [comment]
Fixed by 7ff5a09f1a6a1cbe1295b26da823df443e27e112. Closed.
